# Docker Compose for Resume Matcher
version: '3.8'

services:
  resume-matcher:
    build: .
    ports:
      - "3000:3000"  # Frontend
      - "8000:8000"  # Backend API
    environment:
      - NODE_ENV=production
      - PYTHONPATH=/app/backend
    volumes:
      - ./data:/app/data  # For persistent data if needed
    restart: unless-stopped

  # Optional: Add a database service if needed
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: resume_matcher
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:
